# Generated by Django 5.1.4 on 2024-12-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp2_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facture',
            new_name='Bill',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='date_issued',
            new_name='date',
        ),
    ]
