# Generated by Django 5.1.4 on 2024-12-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp2_app', '0002_rename_facture_bill_rename_date_issued_bill_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
