# Generated by Django 5.1.4 on 2024-12-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp2_app', '0004_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
