# Generated by Django 5.1.4 on 2024-12-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp2_app', '0005_client_last_login_mechanic_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='last_login',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
