# Generated by Django 5.1.4 on 2024-12-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp2_app', '0005_client_last_login_mechanic_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='mechanic',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='mechanic',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
